# Generated by Django 3.2.18 on 2023-02-19 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_myuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_date', models.DateField()),
                ('auction_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('chit_amount', models.PositiveBigIntegerField()),
                ('period', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pay_due_date', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('current_installment', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customerchit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_payment_count', models.PositiveIntegerField()),
                ('chittal_number', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.account')),
                ('chitid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.chit')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=30)),
                ('des', models.CharField(max_length=150)),
                ('roi', models.FloatField(default=0.0)),
                ('min', models.PositiveBigIntegerField(default=0)),
                ('max', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=60)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('type', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won_amount', models.PositiveBigIntegerField()),
                ('security', models.FileField(max_length=255, null=True, upload_to='docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.auction')),
                ('cust_chitid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customerchit')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('transactionid', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cust_chitid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customerchit')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chitid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.chit')),
            ],
        ),
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.FileField(max_length=255, null=True, upload_to='docs/')),
                ('proof', models.FileField(max_length=255, null=True, upload_to='docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Customerloan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.PositiveBigIntegerField()),
                ('min_date', models.DateField(null=True)),
                ('max_date', models.DateField(null=True)),
                ('emi', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.account')),
                ('loanid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.loan')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='chitid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.chit'),
        ),
        migrations.CreateModel(
            name='Accountrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=60)),
                ('marital_status', models.CharField(max_length=15)),
                ('namefms', models.CharField(max_length=25)),
                ('dependants', models.PositiveIntegerField(default=0)),
                ('nationality', models.CharField(max_length=25)),
                ('occupation', models.CharField(max_length=25)),
                ('income', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=15, null=True)),
                ('pan', models.CharField(max_length=20)),
                ('aadhar', models.CharField(max_length=20)),
                ('nomname', models.CharField(max_length=25)),
                ('nomaddress', models.CharField(max_length=60)),
                ('relation', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('status', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='accrid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.accountrequest'),
        ),
    ]
